name: Python Vulnerability Scan
on:
  push:
    branches:
      - '*'
      - '*/**'
    paths:
      - func_ai/**

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: amikos-tech/py-vulnerability-scanner@main
        with:
          input-dir: './func_ai'
          format: 'json'
          bandit-config: 'bandit.yaml'
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: |
            ./bandit-*.json